(self.AMP=self.AMP||[]).push({n:"amp-auto-lightbox",ev:"0.1",l:true,v:"2104302228000",m:0,f:(function(AMP,_){
'use strict';function g(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}g(this);"function"===typeof Symbol&&Symbol("x");var m;function r(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function t(a){return a?Array.prototype.slice.call(a):[]};var u=self.AMP_CONFIG||{},v=("string"==typeof u.cdnProxyRegex?new RegExp(u.cdnProxyRegex):u.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function w(a){if(self.document&&self.document.head&&(!self.location||!v.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}u.cdnUrl||w("runtime-host");u.geoApiUrl||w("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var x=self.__AMP_LOG;function y(){if(x.dev)return x.dev;throw Error("failed to call initLogConstructor");};function z(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return A(a,b)}function B(a,b){var c=C(a);c=D(c);return A(c,b)}function C(a){return a.nodeType?z((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function D(a){a=C(a);return a.isSingleDoc()?a.win:a}function A(a,b){E(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function E(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var F={bubbles:!0,cancelable:!0};function G(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}
function H(a){return a.closest?a.closest("a[href],amp-script,amp-story,button,amp-lightbox,amp-carousel,[placeholder],[data-amp-auto-lightbox-disable],amp-selector [option],[subscriptions-action]"):G(a,function(b){var c=b.matches||b.webkitMatchesSelector||b.mozMatchesSelector||b.msMatchesSelector||b.oMatchesSelector;return c?c.call(b,"a[href],amp-script,amp-story,button,amp-lightbox,amp-carousel,[placeholder],[data-amp-auto-lightbox-disable],amp-selector [option],[subscriptions-action]"):!1})}
function I(a){a.tagName.startsWith("AMP-");if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new r;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};/nochunking=1/.test(self.location.hash);(function(){return m?m:m=Promise.resolve(void 0)})();function J(a,b){var c={needsRootBounds:!1},d=c=void 0===c?{}:c,f=d.needsRootBounds;return new b.IntersectionObserver(a,{threshold:d.threshold,root:b.parent&&b.parent!=b&&f?b.document:void 0})}new WeakMap;new WeakMap;var K,L;function M(a){K||(K=new WeakMap,L=new WeakMap);var b=L.get(a);b||(b=J(function(c){for(var d=new Set,f=c.length-1;0<=f;f--){var k=c[f].target;d.has(k)||(d.add(k),b.unobserve(k),K.get(k).resolve(c[f]),K.delete(k))}},a),L.set(a,b));return b}function N(a){if(K&&K.has(a))return K.get(a).promise;M(a.ownerDocument.defaultView).observe(a);var b=new r;K.set(a,b);return b.promise};var O={Article:!0,NewsArticle:!0,BlogPosting:!0,LiveBlogPosting:!0,DiscussionForumPosting:!0};function P(){}var Q=/\s+([0-9]+)w(,|[\S\s]*$)/g;function R(a){return B(a,"mutator").mutateElement(a,function(){a.setAttribute("i-amphtml-auto-lightbox-visited","")})}function S(a){return I(a).then(function(b){return b.signals().whenSignal("load-end")})}
function T(a){return t(a.getRootNode().querySelectorAll('script[type="application/ld+json"]')).map(function(b){try{var c=JSON.parse(b.textContent)}catch(d){c=null}return(c||{})["@type"]}).filter(Boolean)}function U(a){return T(a).some(function(b){return O[b]})}function V(a){function b(c){return!!a.getRootNode().querySelector(c)}return b('script[custom-element="amp-lightbox-gallery"]')&&b("[lightbox]:not([i-amphtml-auto-lightbox-visited])")}var W=0;
function X(a,b){return B(a,"mutator").mutateElement(b,function(){b.setAttribute("lightbox","i-amphtml-auto-lightbox-"+W++)}).then(function(){z(a.win,"extensions").installExtensionForDoc(a,"amp-lightbox-gallery");var c=b.ownerDocument.createEvent("Event");c.data={};c.initEvent("amp-auto-lightbox:newly-set",F.bubbles,F.cancelable);b.dispatchEvent(c);return b})}
function Y(a,b){b.map(function(c){return S(c).then(function(){return N(c).then(function(d){var f=d.boundingClientRect;if(d=c.signals().get("load-end")){d=f.width;var k=f.height,n=c.querySelector("img"),l=n.naturalWidth;var h=n.naturalHeight;var q=l/h;var e=-1;if(n=n.getAttribute("srcset"))for(var p;p=Q.exec(n);)p=parseInt(p[1],10),p>e&&(e=p);h=e>l?{naturalWidth:e,naturalHeight:e/q}:{naturalWidth:l,naturalHeight:h};l=h.naturalWidth;h=h.naturalHeight;e=B(c,"viewport").getSize();q=e.width;e=e.height;
d*=k;if(d=1.2<=l*h/d||l>q||h>e||.25<=d/(q*e))H(c)?d=!1:(d=C(c),d=D(d),d=!(E(d,"action")?A(d,"action"):null).hasResolvableAction(c,"tap"))}if(d)return y().info("amp-auto-lightbox","apply",c),X(a,c)})},P)})}
function Z(a,b){if(V(a))var c=0;else c=(c=a.getRootNode().querySelector('meta[property="og:type"]'))?c.getAttribute("content"):void 0,c="article"==c||U(a);c?(c=t((b||a.win.document).querySelectorAll("amp-img:not([lightbox]):not([i-amphtml-auto-lightbox-visited])")),c.forEach(R),Y(a,c)):y().info("amp-auto-lightbox","disabled")}(function(a){var b=a.ampdoc;b.whenReady().then(function(){b.getRootNode().addEventListener("amp:dom-update",function(c){Z(b,c.target)});Z(b)})})(self.AMP);
})});

//# sourceMappingURL=amp-auto-lightbox-0.1.js.map
